name: Release binaries

on: 
  push:
    branches: 
      - "main"
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
  
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.yarn
          ~/.pkg-cache
        key: dependencies-js-18-${{ hashFiles('package.json') }}

    - name: Prepare build
      run: |
        yarn
        yarn dist
        ./dist/index-linux --help

    - name: Upload Release assets
      if: github.event_name == 'release'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload ${{ github.event.release.tag_name }} ./dist/index-linux ./dist/index-macos ./dist/index-win.exe
